[package]
name = "converter-json"
description = "Converter CSV/YAML to JSON"
authors = ["Hkmori15"]
repository = "https://github.com/Hkmori15/Converter-json"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
csv = "1.3"
serde_yaml = "0.9.33"
